export default {
  update_button: "Atualizar meus dados",
  fields: [
    {
      name: "Nome Social",
      field: "social_name",
      type: "text",
      placeholder: "Qual é o seu nome?",
      disabled: false,
      value: "",
    },
    {
      name: "Apelido",
      field: "surname",
      type: "text",
      placeholder: "Como é o seu apelido?",
      disabled: false,
      focus: true,
    },
    {
      name: "CEP",
      field: "zip_code",
      type: "zip_code",
      placeholder: "Qual é o seu CEP?",
      disabled: false,
    },
    {
      name: "Rua",
      field: "street",
      type: "text",
      placeholder: "Qual é a sua rua?",
      disabled: false,
    },
    {
      name: "Número",
      field: "number",
      type: "text",
      placeholder: "Qual é o número da sua casa?",
      disabled: false,
    },
    {
      name: "Bairro",
      field: "neighborhood",
      type: "text",
      placeholder: "Qual é o seu bairro?",
      disabled: false,
    },
    {
      name: "Cidade",
      field: "city",
      type: "text",
      placeholder: "Qual é a sua cidade?",
      disabled: false,
    },
    {
      name: "Estado",
      field: "state",
      type: "text",
      placeholder: "São Paulo",
      disabled: true,
    },
    {
      name: "Telefone",
      field: "phone",
      type: "phone",
      placeholder: "Qual é o seu telefone?",
      disabled: true,
    },
    {
      name: "Data de Nascimento",
      field: "date_of_birth",
      type: "date",
      placeholder: "Qual é a sua data de nascimento?",
      disabled: false,
    },
    {
      name: "Genêro",
      field: "gender",
      type: "dropdown",
      placeholder: "Qual é o seu gênero?",
      disabled: false,
    },
  ],
};
